### ISSUE TITLE
Documentation and examples needed

### ISSUE THREAD

**Issue by creotiv** [IBM/pytorchpipe#93]
It would be very nice to see at least some simple docs and examples on how to use this lib right.

Thanks

**Comment by tkornut** [comment]
Just updated the readme and added a "quick start" section. Hope it helps for now, feedback appreciated! 👍

**Comment by tkornut** [comment]
Update: shared tutorial presentation on zenodo:
https://zenodo.org/record/3269928

Closing this issue for now. Looking for feedback! ;)
